name: Branch Protection

on:
  push:
    branches: [ master, develop ]

jobs:
  enforce-branch-protection:
    name: 🛡️ Enforce Branch Protection
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Check if push is allowed
        uses: actions/github-script@v6
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            
            if (branch === 'main') {
              core.setFailed('❌ Direct pushes to main branch are not allowed! Please create a PR.');
            }
            
            if (branch === 'develop' && context.actor !== 'github-actions[bot]') {
              const { data: pr } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: `${context.repo.owner}:${branch}`,
                state: 'open'
              });
              
              if (pr.length === 0) {
                core.setFailed('❌ Direct pushes to develop branch should go through PR process!');
              }
            }